### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/dms#213]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] dms - By @vancouver29 - #262
- [x] dms_attachment_link - By @victoralmau - #371
- [x] dms_auto_classification - By @victoralmau - #322
- [x] dms_field - By @CarlosRoca13 - #339
- [x] dms_field_auto_classification - By @victoralmau - #336
- [x] dms_user_role - By @victoralmau - #321

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by satriani-vai** [comment]
Any progress?

**Comment by pedrobaeza** [comment]
Not yet. If you want to fund the migration, contact any of the contributors of the modules.

**Comment by lijoantony** [comment]
I believe a PR is underway https://github.com/OCA/dms/pull/249

**Comment by pedrobaeza** [comment]
That PR is invalid with red CI and even not installing (and no commit history, but that's just a technical detail).

**Comment by jasonribble** [comment]
Any way I can help? I'm new to OCA modules though I'd be happy to put my energy into this module.

**Comment by pedrobaeza** [comment]
You can try to migrate it with the guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0, but the hard part here is that you should convert JS code to OWL, and that's not an easy task I'm afraid.

**Comment by jasonribble** [comment]
Is anyone working on it yet?

**Comment by pedrobaeza** [comment]
Nobody has expressed interest yet, and the existing PR is not working at all and no more answers from the original author.

**Comment by vancouver29** [comment]
Hi all, I will take time to migrate these 2 modules if no one has started yet?

**Comment by jasonribble** [comment]
How exciting! I'm unsure how I can help but feel free to reach out?

**Comment by agent-z28** [comment]
@vancouver29 did you start already something ?

**Comment by vancouver29** [comment]
@agent-z28 I just started; it will take time. The 2 OCA dependencies, `web_drop_target` and `mail_preview_base,` should also be migrated into v16. As far as I know, the OCA Module `web_drop-target` functionality should now be in Odoo core.

**Comment by agent-z28** [comment]
@vancouver29 thats great! I know that from Elego in Berlin they are planing to work on that topic!
I send them the Link again, to contact you and collaborate on this topic.

**Comment by len-foss** [comment]
I tested some things, and I'm really not sure of the best approach to port most of the js.
There's a lot of work in porting `mail_preview_base` (https://github.com/OCA/social/pull/1183); I haven't even checked `web_drop_target` (https://github.com/OCA/web/pull/2528/). 

It seems that some of the functionality in core that should be reusable is fairly coupled to the way it's used in enterprise code making it a bit awkward. There are some design decisions to take, in any case.

**Comment by vancouver29** [comment]
@agent-z28 @len-foss FYI, the `dms` module is nearly complete. We no longer need the two OCA modules `web_drop_target` and `mail_preview_base`, because Odoo Core 16 provides the functionalities offered by these two OCA modules. When the time comes, I will create a pull request as soon as possible.

**Comment by len-foss** [comment]
@vancouver29 Nice! Don't hesitate to ping me before it's entirely finished, I'm already running a 16 test instance with a quickly hacked branch (without js preview) so I can also check everything migrates properly and do some cleanup if needed.

In the meantime I've worked on some related features:
- https://github.com/OCA/knowledge/pull/431 which contains indexation of content with pyMupdf and tesseract for OCR (there may be other more interesting options to consider for OCR)
- a related on indexed content so that documents can be searched on their content, taking advantage of that indexation
- automatic tagging of documents by fuzzy-matching tag names with indexed content (and similar a categorization)
- and a few miscellaneous features

(I've made some tests with PrivateGPT that didn't really work out with non-English language, but that could be something really useful to integrate, I'd be interested to know if anybody else is working on something like this.)

Let me know if I should make a PR for any of it.

**Comment by agent-z28** [comment]
@len-foss please contact me about AI related document processing, since we have this topic in a quite high priority and did some research based on this! We should join efforts and provide a good solution for the oca

**Comment by vancouver29** [comment]
@agent-z28 @len-foss and OCA community FYI, I created a PR for the `DMS` module. [PR 262](https://github.com/OCA/dms/pull/262)

**Comment by vancouver29** [comment]
@pedrobaeza @marylla FYI https://github.com/OCA/dms/pull/262#issuecomment-1793380467

**Comment by mpoli** [comment]
As per https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list are we missing  dms_attachment_link in the list of modules?

I have installed the dms app but I cannot see the functionality described in that module happening without it.

**Comment by pedrobaeza** [comment]
It's not migrated. Being in the list or not doesn't change this question.

**Comment by mpoli** [comment]
Thanks for the prompt reply. I was trying to understand wether the functionality provided by that module will be made available somehow in 16, and thought that this section of that referred document might be of help, as I didn't see it in the list, even if crossed out:

> So that doesn't mean the module is not needed in new version. This has to be checked by any contributor. If finally not needed, then the line for the module should be on the migration issue, but it should be crossed out by any of the maintainers, explaining the reason why it's not needed.

But what I am searching is the functionality that the dms_attachment_link  module provides in v15 for Odoo 16. That is, being able to select a file that is in DMS as an attachment to chatter, email, SMS etc especially in sales and CRM so we can send clients information that is frequently requested. 

Will there be any way to do that in 16?

**Comment by pedrobaeza** [comment]
Someone needs to migrate the module.

**Comment by R3D2** [comment]
> Thanks for the prompt reply. I was trying to understand wether the functionality provided by that module will be made available somehow in 16, and thought that this section of that referred document might be of help, as I didn't see it in the list, even if crossed out:
> 
> > So that doesn't mean the module is not needed in new version. This has to be checked by any contributor. If finally not needed, then the line for the module should be on the migration issue, but it should be crossed out by any of the maintainers, explaining the reason why it's not needed.
> 
> But what I am searching is the functionality that the dms_attachment_link module provides in v15 for Odoo 16. That is, being able to select a file that is in DMS as an attachment to chatter, email, SMS etc especially in sales and CRM so we can send clients information that is frequently requested.
> 
> Will there be any way to do that in 16?

Seems to have been done here, but a step is still missing for it to be integrated https://github.com/OCA/dms/pull/311#issue-2182803904

**Comment by CarlosRoca13** [comment]
Working on dms_field

**Comment by fanchlegal** [comment]
@CarlosRoca13 : Do you need some help to do it ?

**Comment by CarlosRoca13** [comment]
Thanks @fanchlegal, I will try to have it between this or next week, if I need some help I will ask you

**Comment by fanchlegal** [comment]
@CarlosRoca13 : You're welcome, do not hesitate !

**Comment by agent-z28** [comment]
@sbidoul is anthing missing or can it be closed  ? ;)
